Blog app - create a data model
Marcraphael12/rails_blog_app pull request #1
Opened 2023-08-22 19:43 UTC by Marcraphael12

### Project requirements
Be sure to reference the [ERD diagram](../images/blog_app_erd.png) from the sneak peek if you have any questions about table or column names or data relationships.

- Create a new app. Give it a meaningful name.
- Initialize your project with Git.
- Make sure that your project has Postgres database set up.
- Build your project schema.
    - Create and run the necessary migration files.
    - Table and column names should match the ERD diagram.
        - note: photo for users table should be a link to an image
    - Foreign keys should be included.
        - Pay attention that in `posts` table the column holding the foreign key to the `users` table should be named `author_id`
    - All columns that are foreign keys should have a corresponding index.

2023-08-22 20:04 UTC, Qoosim reviewed
#  *Status: Invalid Request* :red_circle: 

Hi @Marcraphael12, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif)

## Invalid Code Review Request

You have submitted a project, that does not have linter setup. Kindly [check here](https://github.com/microverseinc/linters-config) to setup the linter for your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-22 23:10 UTC, 1GORDON reviewed
##
## Hi @Marcraphael12 ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [x] You have submitted a project with a readme file that is not well customized. Kindly check your general requirements and customize your readme file accordingly.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-23 03:56 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @Marcraphael12, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- Migration files to create corresponding tables have been added :+1: 


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-23 03:56 UTC, FrederickMih commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [ ] Please make sure your MIT license link is working in order to render your README file professional :+1: I got the 404 error page since you are referencing an unexciting file here. You created MIT.md file and also, make sure both date and name section in the license file are up to date :+1:

2023-08-23 03:56 UTC, FrederickMih commented on README.md
>    <br/>
- [ ] You'll kindly required to replace this logo with your own else get rid of it :+1:

2023-08-23 03:56 UTC, FrederickMih commented on db/migrate/20230822191809_add_user_ref_to_post.rb
> +    add_reference :posts, :user, null: false, foreign_key: true
- [ ] Hi @Marcraphael12, once more kindly check the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) again. We are told to create author_id column in the posts table not the default user_id. Let's adhere to the requirements of the project.

2023-08-23 03:56 UTC, FrederickMih commented on db/migrate/20230822190037_create_comments.rb
> +      t.references :user, null: false, foreign_key: true
- [ ] As mentioned above :arrow_up: , we need author_id not user_id column in the comments table as reference key. **Hints**

` t.references :author, foreign_key: { to_table: 'users' }`

2023-08-23 03:56 UTC, FrederickMih commented on db/migrate/20230822185757_create_likes.rb
> +      t.references :user, null: false, foreign_key: true
- [ ] Kindly check comments above :arrow_up:

2023-08-23 14:10 UTC, mckent05 approved these changes
Hi @Marcraphael12, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- Good job setting up your database makeup 👍 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-23 14:32 UTC, merged