Blog app: Validations and spec
Marcraphael12/rails_blog_app pull request #4
Opened 2023-08-25 11:12 UTC by Marcraphael12

### Project requirements
- Add the following validations:
  - For the User model:
    - Name must not be blank.
    - PostsCounter must be an integer greater than or equal to zero.
  - For the Post model:
    - Title must not be blank.
    - Title must not exceed 250 characters.
    - CommentsCounter must be an integer greater than or equal to zero.
    - LikesCounter must be an integer greater than or equal to zero.
- Add unit specs for all of your models' methods and validations.

2023-08-25 12:20 UTC, Munsa1 requested changes
Hi @Marcraphael12, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Passing Test Cases :heavy_check_mark: 
Added Validations To Models As Requested Here #3 :heavy_check_mark: 
Descriptive Pr :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Please do not open a new PR, make required changes here and resubmit for another review
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 14:34 UTC, Marcraphael12 commented on spec/models/post_spec.rb
>    end
done

2023-08-25 14:55 UTC, Marcraphael12 commented on spec/models/user_spec.rb
already have a method to check thath

2023-08-25 15:03 UTC, Marcraphael12 commented on spec/models/user_spec.rb
in post

2023-08-25 15:14 UTC, Marcraphael12 commented on spec/models/user_spec.rb
>    end
done

2023-08-25 15:37 UTC, Gambit142 requested changes
Hi @Marcraphael12 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- Setup linters correctly ✔️ 
- Use of Rspec to test models ✔️ 
- Wrote validations for model attributes ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 15:37 UTC, Gambit142 commented on app/models/post.rb
- [ ] The previous reviewer requested that it is not a good practice to allow nil values for the `LikesCounter` and the `CommentsCounter`. Allowing `nil` value is against the project's requirement as these counters should be of `integer` data types and `nil` is a different data type. In a real-life setting, the Postcounter will be from number zero and upwards. Kindly implement this change. 👍 😎

2023-08-25 15:37 UTC, Gambit142 commented on app/models/user.rb
> +
- [ ] The previous reviewer requested that it is not a good practice to allow nil values for the `PostCounter` Allowing `nil` value is against the project's requirement as this counter should be of `integer` data type and `nil` is a different data type. Kindly implement this change. In a real-life setting, the Postcounter will be from number zero and upwards. 👍 😎

2023-08-25 15:37 UTC, Gambit142 commented on spec/models/user_spec.rb
- [ ] It is good that you are testing it in another file but based on the requirement, all methods in a class should be tested in their `spec` file. This also improves the organization and each class and its methods can be tested in a `spec` file. Kindly implement the change. 👍

2023-08-25 15:37 UTC, Munsa1 commented on spec/models/user_spec.rb
- [ ] No in the user model you have a `update_posts_counter` method that has not been tested in the `user_spec.rb` file.

Your user.rb file
![image](https://github.com/Marcraphael12/rails_blog_app/assets/81932478/be05fdd3-b464-48c3-95e7-55e24935b29a)

Your user_spec file
![image](https://github.com/Marcraphael12/rails_blog_app/assets/81932478/131541bc-dab1-4f9a-ab11-f362de30e681)

2023-08-26 01:49 UTC, Reem-lab approved these changes
# Hi @Marcraphael12, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ]  Followed Gitflow 💯
- [ ]  Descrtipive PR⭐
- [ ] Kudos for working on the validations🤩
- [ ] No Linters error ✅ 
- [ ] All tests passed ⭐
- [ ] Amazing job working on the requested changes 💯

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 03:48 UTC, merged